#include <stdlib.h>
#include <stdio.h>
#include <string.h>

FILE* openFile(char *name, char *mode){
	if(name == 0) return NULL;
	return fopen(name, mode);
}

void closeFile(FILE *file){
	fclose(file);
}

void writePPMHeader(FILE *file, int height, int width){
	fprintf(file, "P3\n");
	fprintf(file, "%d %d\n", width, height);
	fprintf(file, "255\n");
	fprintf(file, "# This was auto generated by joeb3219/procgen.\n");
	fprintf(file, "# Height is %d, width is %d.\n", height, width);
}

void writePPMColor(FILE *file, int rgb){
	int r, g, b;
	r = (rgb & 0xFF0000) >> 16;
	g = (rgb & 0x00FF00) >> 8;
	b = (rgb & 0x0000FF);
	fprintf(file, "%d %d %d ", r, g, b);
}

void writePPMNewLine(FILE *file){
	fprintf(file, "\n");
}

void append(char *str, char c){
	char buff[2] = {c, '\0'};
	strcat(str, buff);
}

double getNextDoubleToken(FILE *file){
	char *str = calloc(8, sizeof(char)), c, tokenCount = 0;
	double d = 0;
	while( (c = fgetc(file)) != EOF){
		if(c == ' ' || c == '\t' || c == '\n'){
			if(tokenCount != 0){
				sscanf(str, "%lf", &d);
				return d;
			}
			continue;
		}else{
			tokenCount ++;
			if(tokenCount % 8 == 0) str = realloc(str, (tokenCount + 8) * sizeof(char));
			append(str, c);
		}
	}
	return d;
}
